# Generated by Django 4.1.3 on 2023-04-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
