# Generated by Django 4.1.3 on 2023-03-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmreco',
            name='user',
        ),
        migrations.RemoveField(
            model_name='option',
            name='alarmHst',
        ),
        migrations.RemoveField(
            model_name='sleephst',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sleepreco',
            name='user',
        ),
        migrations.RenameField(
            model_name='passinput',
            old_name='passwordInput',
            new_name='passwordIn',
        ),
        migrations.DeleteModel(
            name='AlarmHst',
        ),
        migrations.DeleteModel(
            name='AlarmReco',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='SleepHst',
        ),
        migrations.DeleteModel(
            name='SleepReco',
        ),
    ]
