# Generated by Django 4.1.3 on 2023-03-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_alarmreco_user_remove_option_alarmhst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwordContent', models.CharField(max_length=50)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devices')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.user')),
            ],
        ),
    ]
