# Generated by Django 4.1.3 on 2023-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_outstandingtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehst',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='time_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sessionset',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sessionset',
            name='time_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='setdevice',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
