# Generated by Django 4.1.3 on 2023-05-04 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_devicehst_time_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceauto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deviceauto',
            name='time_stamp',
            field=models.CharField(max_length=100),
        ),
    ]
