# Generated by Django 4.1.3 on 2023-05-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_deviceauto_user_alter_deviceauto_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehst',
            name='time_stamp',
            field=models.CharField(max_length=100),
        ),
    ]
